apiVersion: v1
kind: Service
metadata:
  name: tonic-queue
  labels:
    app: tonic-queue
spec:
  ports:
  - name: "amqp"
    port: 5672
    targetPort: 5672
  selector:
    app: tonic-queue
status:
  loadBalancer: {}
