apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonic-pii-detection
  labels:
    app: tonic-pii-detection  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-pii-detection
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-pii-detection
    spec:
      containers:
      - env:
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        image: {{ .Values.dockerRepoBaseUrl }}/tonic_pii_detection:{{ .Values.dockerImageTag }}
        imagePullPolicy: ""
        name: tonic-pii-detection
        ports:
        - containerPort: 7687
        resources:
          requests:
            cpu: 125m
            memory: 2Gi
          limits:
            cpu: 250m
            memory: 3Gi
      restartPolicy: Always
      serviceAccountName: ""
