apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonic-web-server
  name: tonic-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-web-server
    spec:
      containers:
      - env:
        - name: TONIC_AMPQP_URL
          value: amqp://{{ .Values.rabbitMq.user }}:{{ .Values.rabbitMq.password }}@tonic-queue:5672/
        - name: TONIC_DB_DATABASE
          value: {{ .Values.tonicdb.dbname }}
        - name: TONIC_DB_USERNAME
          value: {{ .Values.tonicdb.user }}
        - name: TONIC_DB_PASSWORD
          value: {{ .Values.tonicdb.password }}
        - name: TONIC_DB_PORT
          value: {{quote .Values.tonicdb.port }}
        - name: TONIC_DB_SSLMODE
          value: {{ .Values.tonicdb.sslMode }}
        - name: TONIC_DB_HOST
          value: {{ .Values.tonicdb.host }}
        - name: TONIC_STATISTICS_SEED
          value: {{quote .Values.tonicStatisticsSeed }}
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        image: {{ .Values.dockerRepoBaseUrl }}/tonic_web_server:{{ .Values.dockerImageTag }}
        imagePullPolicy: ""
        name: tonic-web-server
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: 125m
            memory: 1Gi
          limits:
            cpu: 250m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
