apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonic-queue
  labels:
    app: tonic-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-queue
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-queue
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitMq.password }}
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitMq.user }}
        image: rabbitmq:3.6.6-management
        imagePullPolicy: ""
        name: tonic-queue
        ports:
        - containerPort: 5672
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
